// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Runtime traffic uses Supabase's transaction pooler, while schema changes
    // need the session/direct connection because `prisma db push` uses DDL and
    // advisory locking that transaction pooling cannot reliably support.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
